from typing import Optional

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class Session:
    def __init__(self, project: str, request: str, checkpoint: Optional[str] = None) -> None: ...
    def advance(self, max_work: int, cancel: CancellationToken) -> str: ...
    def result(self) -> str: ...
    def checkpoint(self) -> str: ...
    @property
    def is_finished(self) -> bool: ...

def call(op: str, input: str) -> str: ...
def evaluate(input: str, cancel: CancellationToken) -> str: ...
